import logging
import time
import ray
from threading import Thread
from typing import List
import torch
import time

import queue
from paceserve.disutil.instance import Instance
from paceserve.utils.threading_utils import synchronized
from paceserve.utils.timer_utils import Timer
from paceserve.core.datatypes.kv_cache_obj import KVmetadata, KVobj
from paceserve.core.datatypes.sequence import Sequence
from paceserve.config.config import DecodeSchedulerConfig
from paceserve.core.datatypes.request_output import RequestOutput
from paceserve.utils.throttled_logger import ThrottledLogger

logger = logging.getLogger(__name__)
t_logger = ThrottledLogger()


@ray.remote
class DecodeInstance(Instance):

    def __init__(
        self,
        *args, **kwargs) -> None:
        args_list = list(args) 
        config = args_list[2]
        config.scheduler_config = DecodeSchedulerConfig(
            max_batched_tokens=config.scheduler_config.max_batched_tokens,
            max_num_seqs=config.scheduler_config.max_num_seqs,
            allow_drop_requests = config.scheduler_config.allow_drop_requests,
            request_drop_threshold = config.scheduler_config.request_drop_threshold,
            ttft_slo = config.scheduler_config.ttft_slo,
            tbt_slo = config.scheduler_config.tbt_slo
        )
        args_list[2] = config
        super().__init__(*args, **kwargs)
        self.transfer_ct = 0

        # There are three threads named A, B, and C.
        # A thread executes the run method whereas the
        # B thread is trapped in _kv_cache_insertion and C
        # is the interupt generated by the controller in add_kvc_metadata
        self.kvc_allocate_memory = queue.Queue() # allocate memory (C -> A)
        self.kvc_transfer = queue.Queue() # get the kv cache from the instance (B -> A)
        self.kvc_add_to_run = queue.Queue() # put sequence in the running queue (B -> A)
        self.spawn_threads(self._kv_cache_insertion, 4)
        self.spawn_threads(self._preempted_kv_insertion, 4)
        self.total_inserted = 0
        
        self._tmp_transfer_times = dict()
    
    def spawn_threads(self, target_func, count):
        for _ in range(count):
            thread = Thread(target=target_func)
            thread.start()
    
    def warmup(self) -> None:

        is_completed = False
        while not is_completed:
            if self.kvc_allocate_memory.qsize() > 0:
                kv_metadata: KVmetadata = self.kvc_allocate_memory.queue[0]
                self.llm_engine.seq_manager.add_seq(kv_metadata.seq)
                result = self.llm_engine.allocate_for_kvcache(kv_metadata)
                # its warmup, assuming having enough memory for warmup
                if result:
                    kv_metadata = self.kvc_allocate_memory.get()
                    self.kvc_transfer.put(kv_metadata)
                else:
                    self.llm_engine.seq_manager._free_seq(kv_metadata.seq.seq_id)
                    break
                # waiting for kv cache insertion to do the magic
                while self.kvc_add_to_run.qsize() <= 0: pass
                seq: Sequence = self.kvc_add_to_run.get()
                self.llm_engine.add_decode_sequence(seq)
                
            step_outputs = self.llm_engine.step()
            if step_outputs:
                is_completed = step_outputs[0].finished
    
    def _run(self) -> None:
        self.start_time = time.monotonic()

        while not self.terminate:
            step_outputs: List[RequestOutput] = self.llm_engine.step()
            self.num_steps += 1
            self._on_step_complete()

            for output in step_outputs:
                if output.finished:
                    self.num_processed_requests += 1
                    self.finished_seq(output)
                    if self.calculate_rouge:
                        self.rouge_dic[output.seq_id]["pred"] = [output.text.split('.')[0]]
                    # skip those with unknown tokens
                    if output.nll and self.use_logits:
                        self.num_token_processed += output.token_count
                        self.nll_sum += output.nll
                        t_logger.log(
                            key='instance.run',
                            message=f'nll_sum: {self.nll_sum} num token: {self.num_token_processed} perplexity: {torch.exp(self.nll_sum/self.num_token_processed)}'
                        )
                    t_logger.log(
                        key='instance.run',
                        message=f'num_processed_requests: {self.num_processed_requests} free gpu blocks: {self.llm_engine.scheduler.block_manager.get_num_free_gpu_blocks()}'
                    )
            self.gpu_max_blocks.set(self.llm_engine.config.cache_config.num_gpu_blocks)
            self.gpu_free_blocks.set(self.llm_engine.scheduler.block_manager.get_num_free_gpu_blocks())
        if self.calculate_rouge:
            self._evaluate_rouge()
        logger.debug('Returning from instance')
        self._run_finish.send.remote()
        self.run_loop_finished = True
    
    def add_kvc_metadata(self, metadata):
        self._tmp_transfer_times[metadata.seq.seq_id] = time.time()
        metadata.seq.state._kvmeta_arrive_decode = time.time()
        self.llm_engine.scheduler.kvmeta_queue.put(metadata)
    
    @synchronized
    def _increase_transfer_counter(self):
        self.transfer_ct += 1

    def _insert_kv_cache(self, kv_obj: KVobj):
        seq: Sequence = self.llm_engine.seq_manager.get_seq(kv_obj.seq_id)
        seq.state._kv_transfer_started_at = kv_obj.kv_transfer_start    # time.time on prefill machine
        seq.state._left_prefill_at = kv_obj.left_prefill    # time.monotonic on prefill machine
        seq.state._kv_transfer_finished_at = time.time()
        seq.state._kv_insertion_start = time.monotonic()
        result = self.llm_engine._run_workers(
                '_insert_kv_cache',
                get_all_outputs=True,
                seq=seq,
                kv_obj=kv_obj,
                device = self.device
            )

        if sum(s.status for s in result) == len(result):
            # at the end of completion, the metrics is calculated based on the original seq
            # passed for memory allocation, we alaways refer to original sequence
            seq.state.on_kv_insertion_finished()
            seq.state._worker_kv_insertion = result[0].insertion_time
            seq.state._worker_kv_allocate = result[0].allocate_time
            self.llm_engine.scheduler.pending_decode.put(seq)
            logger.debug(f"total seq finish kv transfer: {self.transfer_ct}")
        else:
            logger.debug(f"this kv insertion failed, {seq} {kv_obj}")
            assert sum(result) == len(result), f"kv cache insertion of seq {seq.seq_id} failed"
        logger.debug(f'kv cache transfer seq {seq.seq_id} took {time.time() - self._tmp_transfer_times[seq.seq_id]}, space on engine: {self.llm_engine.scheduler.block_manager.get_num_free_gpu_blocks()}')
    
    # the sequence in pending_kv_transfer has already being allocate on engine side, so just need to do transfer and insertion
    def _kv_cache_insertion(self):
        pending_refs = []
        while not self.terminate:
            # if there is sequence in the swapped out list, we hold on the kv cache transfer
            while self.llm_engine.scheduler.pending_kv_transfer.qsize() > 0:
                kv_metadata: KVmetadata = self.llm_engine.scheduler.pending_kv_transfer.get()
                kv_metadata.seq.state._kvmeta_get_scheduled = time.time()
                self.llm_engine.seq_manager.add_seq(kv_metadata.seq)
                seq_id = kv_metadata.seq.seq_id
                pending_refs.append(kv_metadata._prefill_instance.transfer_kv_cache.remote(seq_id))

            if pending_refs:
                ready_refs, pending_refs = ray.wait(pending_refs)
                for _id in ready_refs:
                    kvobj = ray.get(_id)
                    self._insert_kv_cache(kvobj)
                    self.total_inserted +=1
                    logger.debug(f"total inserted on instance {self.instance_id}: {self.total_inserted}")
    
    # The pending_kv_insert hold the preemptied sequence kv cache insertion         
    def _preempted_kv_insertion(self):
        while not self.terminate:
            try:
                seq = self.llm_engine.scheduler.pending_kv_insert.get(timeout=0.01)
            except queue.Empty:
                continue
            dram_kvobj = self.llm_engine.preempt_seq_kv[seq.seq_id]
            result = self.llm_engine._run_workers(
                '_insert_kv_cache',
                get_all_outputs=True,
                seq=seq,
                kv_obj=dram_kvobj,
                device=self.device
            )
            assert sum(result) == len(result), f"error transferring seq {seq.seq_id} from DRAM back to GPU"
            self.llm_engine.seq_manager.add_seq(seq)
            self.llm_engine.scheduler.pending_decode.put(seq)
